server:
  port: 8080 #??????
spring:
  application:
    name: goods
  datasource: #???????
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/certificate_electronization?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root #?????
    password: 123456
  servlet:
    multipart: #??????
      max-file-size: 10MB
      max-request-size: 50MB

  main:
    allow-circular-references: true